# This file contains a list of manually declared hosts
# for local network and is read by the root flake file.
# Will be generated by config.yaml

[
  {
    hostname = "nlt"; # static or generated host

    # static or generated users
    users = [
      {
        login = "darkone";
        name = "Darkone Linux";
        profile = "admin";
      }
    ];

    # the "deployment" section of colmena
    deployment = {
      tags = [
        "desktop"
        "admin"
        "local"
      ];
      allowLocalDeployment = true;
    };
  }
  {
    hostname = "test";
    users = [
      {
        login = "darkone";
        name = "Darkone Linux";
        profile = "admin";
      }
    ];
    deployment = {
      tags = [
        "test"
        "admin"
      ];
    };
  }
  {
    hostname = "test2";
    users = [
      {
        login = "darkone";
        name = "Darkone Linux";
        profile = "admin";
      }
    ];
    deployment = {
      tags = [ "test" ];
      targetHost = "ndf-start-iso";
    };
  }
]
