{
  lib,
  pkgs,
  config,
  ...
}:
let
  cfg = config.darkone.host.laptop;
in
{
  options = {
    darkone.host.laptop.enable = lib.mkEnableOption "Laptop host minimal configuration";
  };

  config = lib.mkIf cfg.enable {

    # Load minimal configuration
    darkone.host.minimal.enable = true;

    # Sensors management (WIP)
    boot.kernelModules = [ "coretemp" ];
    environment.systemPackages = with pkgs; [ lm_sensors ];

    # TODO Specific configuration
    #hardware.fancontrol.enable = true;
    #hardware.fancontrol.config = ''
    #  # Configuration file generated by pwmconfig
    #  INTERVAL=10
    #  DEVPATH=hwmon3=devices/platform/dell_smm_hwmon
    #  DEVNAME=hwmon3=dell_smm
    #  FCTEMPS=hwmon3/pwm1=hwmon3/temp1_input
    #  FCFANS=hwmon3/pwm1=
    #  MINTEMP=hwmon3/pwm1=40
    #  MAXTEMP=hwmon3/pwm1=70
    #  MINSTART=hwmon3/pwm1=150
    #  MINSTOP=hwmon3/pwm1=100
    #'';

    services.thermald.enable = true;
  };
}
