{
  imports = [
    ./user/children.nix
    ./user/nix-admin.nix
    ./user/teenager.nix
    ./user/nix.nix
    ./user/advanced.nix
    ./admin/nix.nix
    ./system/i18n.nix
    ./system/documentation.nix
    ./system/core.nix
    ./system/hardware.nix
    ./graphic/gnome.nix
    ./graphic/education.nix
    ./graphic/virt-manager.nix
    ./graphic/packages.nix
    ./graphic/obsidian.nix
    ./host/vm.nix
    ./host/laptop.nix
    ./host/server.nix
    ./host/minimal.nix
    ./host/portable.nix
    ./host/desktop.nix
    ./console/pandoc.nix
    ./console/zsh.nix
    ./console/packages.nix
    ./console/git.nix
    ./service/printing.nix
    ./service/audio.nix
    ./service/httpd.nix
  ];
}
