# DO NOT EDIT, this is a generated file.

{
  imports = [
    ./admin/nix.nix
    ./console/git.nix
    ./console/packages.nix
    ./console/pandoc.nix
    ./console/zsh.nix
    ./graphic/education.nix
    ./graphic/gnome.nix
    ./graphic/music.nix
    ./graphic/obsidian.nix
    ./graphic/packages.nix
    ./graphic/virt-manager.nix
    ./graphic/virtualbox.nix
    ./host/desktop.nix
    ./host/laptop.nix
    ./host/minimal.nix
    ./host/portable.nix
    ./host/server.nix
    ./host/start-img.nix
    ./host/vm.nix
    ./service/audio.nix
    ./service/home-assistant.nix
    ./service/httpd.nix
    ./service/printing.nix
    ./system/core.nix
    ./system/documentation.nix
    ./system/hardware.nix
    ./system/i18n.nix
    ./theme/advanced.nix
    ./theme/children.nix
    ./theme/office.nix
    ./theme/teenager.nix
    ./user/build.nix
    ./user/nix.nix
  ];
}
